
#' Simulate a simple random sample (probability sampling) and a convenience sample (non-probability sampling) from the same population. 
#' The functions can be used to obtain samples from both simulated population data and real population data.
#' @parameter N: population size.
#' @parameter n: sample size.
#' @parameter z: response variable. For simulated population: Z is generated by equation, Z=theta + beta*X + e; say, X is covariate~N(0,1) and e is error term~N(0,1).
#'               For real population, the response Z is already in the data, no simulation of Z is required.
#' @parameter s: a binary variable for convenience sampling; 1: if jth subject from population is selected in the sample and 0: otherwise; 
#'               this binary variable is obtained based on the selection probability, p_j = exp(alpha+gamma*X_j)/(1+exp(alpha+gamma*X_j)); alpha and gamma are parameters 
#'               the user can change implying the relationship between covariate and selection probability. For example, while obtaining a convenient sample in front of a
#'               shopping mall which is usually visited by the people from higher income group. Here, income is X; you can set alpha and gamma so that some people have higher
#'               selection probability (p_j) to be selected in the convenient sample. 
#' @return the function srs_samp returns simple random sample
#' @return the funtion conv_samp returns a convenient sample.
#'
#' @author Harun Mazumder


#part (1)*************************************************************************************
#First, write a function to simulate a simple random sample of size n: (same thing as built-in 'sample' command in R)

srs_samp = function(N, n, z){
           #generate one value from U(0,1) and multiply by N:
           u_N = runif(n = n, min = 0, max = 1)*N
           #now select every u_N th observation in Z:
           y1 = NULL
          for(i in u_N){
             y1 = c(y1, z[i])
            }
           return(y1)
           }

#end of function for obtaining simple random sample 

#**************************************************************************
#function to obtain a convenience sample of size n:

conv_samp = function(s, z, N, n){

            #first try to generate sample of size n 
            try_conv_sam1 = function(s,z, N, n){
                            y2 = NULL  
                           for(j in 1:N){
                              if(s[j]==1){
                              y2 = c(y2, z[j])
                               }
            if(length(y2)==n){break} #if sample size=n, stop here (outcome here: sample size is either <n or =n)
               }
            return(y2)
            }
            #if sample size in try_conv_sam1 <= n, then do the follwoing to ensure sample size = n:
            #<= because it makes the while loop get activated to ensure final sample size in n.
            try_conv_sam2 = NULL  
            while(length(try_conv_sam1(s, z, N, n)) <= n){
                   try_conv_sam2 = c(try_conv_sam2, try_conv_sam1(s,z,N,n))
                                  if(length(try_conv_sam2) >n) {break} #stop here 
                        }
            conv_samp_final = try_conv_sam2[1:n] #pick first n (since here, length(try_conv_sam2)>=n)
            return(conv_samp_final)
            }
            
#end of function for selecting convenient sample 

#*********************************************************************************************************
#first, simulate a population with response Z:
set.seed(100)
N = 5000
theta = 10
x = rnorm(n = N, mean = 0, sd = 1) 
error = rnorm(n = N, mean = 0, sd = 1) 
Z = theta +  beta*x + error
#*********************************************************************************************************

#now select a simple random sample of size 50:

srs_samp(N = 5000, n = 50, z = Z)

 [1] 14.547458  8.109952 18.541167 10.037056  6.756176  4.557395  5.384830 15.411794  8.802681  7.889307
[11]  8.842822 14.191842 17.306071 14.064200  6.524028  9.147943 -1.190529 13.319481 10.101765 11.229603
[21] 11.055024  9.170931 10.022958 13.796601 10.208387  9.777541  9.452534  7.479602 10.400080 11.779886
[31]  6.380455  7.456635 12.206482 15.178931 12.751706  6.776195  5.313553 10.718648  9.058584  6.924323
[41]  9.447864 10.059343  8.228963 16.642616  7.821928  9.941389 10.847381 13.161154  8.758426  9.331636

#*********************************************************************************************************

#select a convenient sample of size 50:

#first generate the selection probabilities to obtain binary variable (s) indicating 
#selection of a subject according to user's convenience.

alpha = 2
gama = 3
p = exp(alpha+gama*x)/(1+exp(alpha+gama*x))
s = rbinom(n = N, size = 1, prob = p)

conv_samp(s = s, N = N, n=50, z=Z )

 [1] 10.176004  9.900130 10.285617 11.223648  9.599288  9.583325  7.886311 12.752085  6.726998  7.915785
[11] 10.675117  8.488661  9.894917  9.192652 10.597778  9.774098 13.136234  4.803930 20.595025  8.167608
[21] 11.762010 11.194009 12.366914  7.871258  9.418255 10.243294  4.741138 11.355389  8.645854 12.349931
[31]  8.752721  8.582355  6.439541  9.430783 10.830832 12.030775 15.728307 13.998093  9.566154 11.523580
[41] 11.398267 10.974574 15.303709  8.082459 15.161928  9.614982 10.482484 14.209777 12.316719 16.159161



